### ISSUE TITLE
可以兼容Python3吗？

### ISSUE THREAD

**Issue by xiaolei16fan** [haizi-zh/scrapy-qiniu#2]
这是错误日志：
```
2018-09-06 15:38:56 [twisted] CRITICAL:
Traceback (most recent call last):
  File "C:\Anaconda3\envs\sunrised-env\lib\site-packages\scrapy\pipelines\media.py", line 68, in from_crawler
    pipe = cls.from_settings(crawler.settings)
  File "C:\Anaconda3\envs\sunrised-env\lib\site-packages\scrapy_qiniu\impl.py", line 164, in from_settings
    cls.EXPIRES = settings.getint('FILES_EXPIRES', sys.maxint)
AttributeError: module 'sys' has no attribute 'maxint'
```
我在本地修改为了`sys.maxsize`，不过为了兼容2和3应该有更好的方法。

**Comment by haizi-zh** [comment]
This package was initially developed and tested with Python 2.7 three years ago. To be frank, I ceased its development a long time ago.

I've never tested it with Python 3. However, I guess with some minor tweaks it should work with Python 3 correctly. You're always welcome to modify the code and, if you would like, to submit pull requests.

Thank you!
